name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.9'
      - name: Build with SwiftPM
        run: swift build --build-tests
