name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.9'
      - name: Build with SwiftPM
        run: |
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
          export SWIFT_FLAGS="-Xswiftc -sdk -Xswiftc $SDKROOT -Xswiftc -no-verify-emitted-module-interface"
          swift build --build-tests $SWIFT_FLAGS -v
